import type { PageBlockSection } from "./schema";

export interface DefaultPageDef {
  slug: string;
  title: string;
  metaDescription: string;
  isSystemPage: boolean;
  sections: PageBlockSection[];
}

export const defaultCorePages: DefaultPageDef[] = [
  {
    slug: "home",
    title: "Bhutan Health Trust Fund — Healthy People, Stronger Bhutan",
    metaDescription:
      "Bhutan Health Trust Fund sustainably finances essential medicines and vaccines for every Bhutanese citizen across all 20 Dzongkhags.",
    isSystemPage: true,
    sections: [
      {
        id: "home-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Healthy People. Stronger Bhutan.",
        subtitle:
          "Sovereign healthcare financing guaranteeing uninterrupted essential medicines and universal vaccines for every citizen across all 20 Dzongkhags.",
        dzongkhaText: "མི་སེར་གཟུགས་ཁམས་བཟང་པོ་དང་ རྒྱལ་ཁབ་སྟོབས་ཤུགས་ཅན།",
        badge: "Royal Charter Statutory Trust Fund",
        bgVariant: "dark",
        primaryCtaText: "Contribute to Corpus (1:1 Matched)",
        primaryCtaUrl: "/get-involved",
        secondaryCtaText: "Explore Commodities Formulary",
        secondaryCtaUrl: "/our-work",
      },
      {
        id: "home-stats",
        type: "stats",
        order: 2,
        isVisible: true,
        title: "Sovereign Health Impact at a Glance",
        subtitle: "Verified national metrics monitored under Royal Audit Authority oversight",
        bgVariant: "warm",
        items: [
          {
            value: "780,000+",
            title: "Citizens Protected",
            description: "Universal healthcare coverage guaranteed across all 20 Dzongkhags",
            icon: "Users",
          },
          {
            value: "438",
            title: "Essential Modern Medicines",
            description: "100% of National Essential Drugs List guaranteed in perpetuity",
            icon: "Pill",
          },
          {
            value: "110",
            title: "Traditional Medicines",
            description: "Indigenous gSo-ba Rig-pa remedies (including 65 core formulations)",
            icon: "Sparkles",
          },
          {
            value: "Nu. 4.8B",
            title: "Endowment Corpus",
            description: "Ring-fenced capital endowment managed under Royal Charter",
            icon: "Coins",
          },
        ],
      },
      {
        id: "home-royal-decree",
        type: "royal_decree",
        order: 3,
        isVisible: true,
        title: "The Royal Mandate of Sustainable Healthcare",
        dzongkhaText: "རྒྱལ་པོའི་བཀའ་ཤོག",
        content:
          "No citizen of Bhutan should ever suffer or be deprived of life-saving medical care due to lack of essential drugs or vaccines. The Bhutan Health Trust Fund stands as a sacred trust of self-reliance for generations to come.",
        badge: "Royal Charter",
        subtitle: "His Majesty The King of Bhutan",
        bgVariant: "warm",
      },
      {
        id: "home-features",
        type: "feature_cards",
        order: 4,
        isVisible: true,
        title: "Key Institutional Pillars",
        subtitle: "Structured governance and supply lines serving the nation",
        bgVariant: "white",
        items: [
          {
            title: "438 Essential & 110 Traditional Medicines",
            description: "Zero-stockout primary, emergency, and traditional healthcare formulary.",
            icon: "Pill",
            badge: "Primary Formulary",
            url: "/our-work",
          },
          {
            title: "Universal Routine Vaccines (4 Antigens)",
            description: "Pentavalent, PCV, HPV, and seasonal influenza vaccines nationwide.",
            icon: "Syringe",
            badge: "Universal Vaccines",
            url: "/our-work",
          },
          {
            title: "Remote Cold-Chain Logistics",
            description: "Solar-powered temperature-controlled logistics reaching highland settlements.",
            icon: "ThermometerSnowflake",
            badge: "Cold Chain",
            url: "/our-work",
          },
          {
            title: "Fiduciary Integrity & Audits",
            description: "100% clean certification from Royal Audit Authority of Bhutan.",
            icon: "ShieldCheck",
            badge: "Statutory Oversight",
            url: "/reports",
          },
        ],
      },
      {
        id: "home-tools",
        type: "interactive_tools",
        order: 5,
        isVisible: true,
        badge: "Interactive Portals & Simulations",
        title: "National Health District Coverage & Matching Tools",
        subtitle: "Direct access to our 20 Dzongkhags cold-chain data, commodities distribution, and contribution matching.",
      },
      {
        id: "home-cta",
        type: "cta_banner",
        order: 6,
        isVisible: true,
        title: "Every Ngultrum is Matched 1:1 by the Royal Government",
        subtitle:
          "Your endowment contribution is permanently ring-fenced. Only investment yields fund medicines, sustaining healthcare in perpetuity.",
        badge: "Permanent Corpus Endowment",
        primaryCtaText: "Make an Official Contribution",
        primaryCtaUrl: "/get-involved",
        secondaryCtaText: "Track a Donation",
        secondaryCtaUrl: "/track-donation",
        bgVariant: "emerald",
      },
    ],
  },
  {
    slug: "about",
    title: "About Us & Royal Mandate | Bhutan Health Trust Fund",
    metaDescription:
      "Learn about BHTF's Royal Charter mandate, Board of Trustees, sustainable endowment model, and history financing medicines and vaccines for Bhutan.",
    isSystemPage: true,
    sections: [
      {
        id: "about-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "A Sacred Covenant for National Self-Reliance",
        subtitle:
          "Established under Royal Charter in 1998 to protect Bhutan from external dependency on vital medicines and vaccines.",
        dzongkhaText: "རྒྱལ་པོའི་བཀའ་ཤོག་དང་ མི་སེར་གཟུགས་ཁམས་སྲུང་སྐྱོབ།",
        badge: "Royal Charter Institution",
        bgVariant: "dark",
        primaryCtaText: "View Board of Trustees",
        primaryCtaUrl: "#trustees",
        secondaryCtaText: "Read Charter Policies",
        secondaryCtaUrl: "/policies",
      },
      {
        id: "about-pillars",
        type: "feature_cards",
        order: 2,
        isVisible: true,
        title: "Core Foundational Values",
        subtitle: "The principles that anchor every Ngultrum managed by the Secretariat",
        bgVariant: "warm",
        items: [
          {
            title: "Our Mission (དམིགས་ཡུལ།)",
            description:
              "To sustainably finance essential drugs and universal vaccines, guaranteeing uninterrupted, equitable access to primary healthcare for every citizen in Bhutan.",
            icon: "Target",
            badge: "Mission",
          },
          {
            title: "Our Vision (མཐོང་སྣང་།)",
            description:
              "A self-reliant, resilient, and sovereign national health financing system where no Bhutanese is ever denied life-saving medicines or vaccines.",
            icon: "Eye",
            badge: "Vision",
          },
          {
            title: "Gross National Happiness",
            description:
              "Health is recognized as an indispensable foundation for Gross National Happiness, ensuring physical, mental, and social well-being.",
            icon: "Heart",
            badge: "GNH Pillar",
          },
          {
            title: "Permanent Corpus Protection",
            description:
              "Core capital is strictly preserved in perpetuity; only audited investment earnings disburse healthcare commodities.",
            icon: "Lock",
            badge: "Corpus Ring-Fence",
          },
        ],
      },
      {
        id: "about-decree",
        type: "royal_decree",
        order: 3,
        isVisible: true,
        title: "Founding Royal Decree",
        dzongkhaText: "མི་དབང་མངའ་བདག་རིན་པོ་ཆེའི་བཀའ་དྲིན་དྲན་གསོ།",
        content:
          "The Bhutan Health Trust Fund shall stand as an enduring pillar of national resilience, safeguarding the health and vitality of our people against all uncertainties.",
        subtitle: "Fourth Druk Gyalpo Jigme Singye Wangchuck",
        badge: "Founding Royal Decree 1998",
        bgVariant: "gold",
      },
      {
        id: "about-cta",
        type: "cta_banner",
        order: 4,
        isVisible: true,
        title: "Join in Strengthening Bhutan's Health Security",
        subtitle:
          "All contributions are doubled by the Royal Government of Bhutan and invested directly into the permanent endowment fund.",
        badge: "Matched Giving",
        primaryCtaText: "Pledge a Contribution",
        primaryCtaUrl: "/get-involved",
        bgVariant: "emerald",
      },
    ],
  },
  {
    slug: "about-organization",
    title: "Our Organization & Mandate | Bhutan Health Trust Fund",
    metaDescription:
      "Statutory founding of BHTF under the Royal Charter, constitutional healthcare rights under Article 9, and the approved Vision & Mission.",
    isSystemPage: true,
    sections: [
      {
        id: "about-org-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Statutory Mandate & Royal Charter",
        subtitle:
          "Established under Royal Charter in 1998 by His Majesty the Fourth Druk Gyalpo to permanently secure free primary healthcare for Bhutan.",
        dzongkhaText: "རྒྱལ་པོའི་བཀའ་ཤོག་དང་ རང་དབང་གཙུག་ལག",
        badge: "Royal Charter Institution",
        bgVariant: "light",
        primaryCtaText: "Read Charter Articles",
        primaryCtaUrl: "/policies",
        secondaryCtaText: "Board of Trustees",
        secondaryCtaUrl: "/about/trustees",
      },
      {
        id: "about-org-pillars",
        type: "feature_cards",
        order: 2,
        isVisible: true,
        title: "Constitutional Mandate & Institutional Pillars",
        subtitle: "Anchored in Article 9 of the Constitution of the Kingdom of Bhutan",
        bgVariant: "warm",
        items: [
          {
            title: "Our Mission (དམིགས་ཡུལ།)",
            description:
              "To mobilise, invest, and prudently manage a dedicated health endowment to generate sustainable income for the financing of essential medicines, vaccines, and related supplies.",
            icon: "Target",
            badge: "Mission",
          },
          {
            title: "Our Vision (མཐོང་སྣང་།)",
            description:
              "A self-reliant, resilient, and sovereign national health financing system where no Bhutanese is ever denied life-saving medicines or vaccines.",
            icon: "Eye",
            badge: "Vision",
          },
          {
            title: "Article 9 Right to Health",
            description:
              "The State shall provide free access to basic public health services in both modern and traditional medicines across all 20 Dzongkhags.",
            icon: "ShieldCheck",
            badge: "Constitution",
          },
          {
            title: "Capital Ring-Fencing",
            description:
              "Under Royal Charter Article 7, the core endowment principal is protected in perpetuity; only audited operational yields are disbursed.",
            icon: "Lock",
            badge: "Sovereign Shield",
          },
        ],
      },
      {
        id: "about-org-decree",
        type: "royal_decree",
        order: 3,
        isVisible: true,
        title: "Royal Charter Enactment Proclamation",
        subtitle: "His Majesty The King of Bhutan",
        dzongkhaText: "མི་དབང་མངའ་བདག་རིན་པོ་ཆེའི་བཀའ་ཤོག",
        content:
          "Free basic healthcare is a fundamental right of our people. The Bhutan Health Trust Fund ensures that our children and future generations shall never face a shortage of life-saving medicines or vaccines.",
        badge: "Royal Charter 2000",
        bgVariant: "gold",
      },
    ],
  },
  {
    slug: "about-trustees",
    title: "Board of Trustees & Governance | Bhutan Health Trust Fund",
    metaDescription:
      "Directory of the High-Level Board of Trustees, ministerial leadership, terms of reference, and statutory fiduciary oversight.",
    isSystemPage: true,
    sections: [
      {
        id: "about-trustees-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "High-Level Board of Trustees",
        subtitle:
          "Ministerial leadership and eminent sovereign trustees providing strategic fiduciary governance and ethical stewardship.",
        dzongkhaText: "འགོ་ཁྲིད་ལྷན་ཚོགས།",
        badge: "Statutory Governance",
        bgVariant: "light",
        primaryCtaText: "Asset Management Committee",
        primaryCtaUrl: "/about/committees",
        secondaryCtaText: "Secretariat Organogram",
        secondaryCtaUrl: "/about/secretariat",
      },
      {
        id: "about-trustees-pillars",
        type: "feature_cards",
        order: 2,
        isVisible: true,
        title: "Fiduciary Governance Roster",
        subtitle: "Ministerial, fiscal, diplomatic, and public sector representation",
        bgVariant: "white",
        items: [
          {
            title: "Lyonpo Tandin Wangchuk",
            description: "Chairperson • Hon'ble Minister for Health, Royal Government of Bhutan. Provides ministerial direction and policy alignment.",
            icon: "Building2",
            badge: "Chairperson",
          },
          {
            title: "Mr. Tshering Dorji",
            description: "Trustee (Finance) • Finance Secretary, Ministry of Finance, RGOB. Supervises sovereign matching and capital ring-fencing.",
            icon: "ShieldCheck",
            badge: "Trustee",
          },
          {
            title: "Ambassador Lesang Wangdi",
            description: "Trustee & Senior Diplomatic Advisor. Oversees multilateral partnerships and international sovereign agreements.",
            icon: "Award",
            badge: "Trustee",
          },
          {
            title: "Dr. Nawang Norbu",
            description: "Trustee & Research Director. Advises on epidemiological formulary priorities and national health research.",
            icon: "Target",
            badge: "Trustee",
          },
        ],
      },
      {
        id: "about-trustees-terms",
        type: "rich_text",
        order: 3,
        isVisible: true,
        title: "Statutory Terms of Reference & Audit Oversight",
        subtitle: "Royal Audit Authority (RAA) Clean Certification",
        content:
          "The Board of Trustees meets bi-annually to review endowment performance, approve annual procurement disbursements to the Department of Medical Services, and review audit disclosures certified by the Royal Audit Authority of Bhutan.",
        bgVariant: "warm",
      },
    ],
  },
  {
    slug: "about-committees",
    title: "Asset Management & Audit Committees | Bhutan Health Trust Fund",
    metaDescription:
      "Fiduciary investment guidelines, Asset Management Committee (AMC) parameters, and Governance & Audit Committee oversight.",
    isSystemPage: true,
    sections: [
      {
        id: "about-comm-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Asset Management & Audit Committees",
        subtitle:
          "Specialized fiduciary bodies safeguarding the permanent endowment through disciplined asset allocation and statutory risk controls.",
        dzongkhaText: "མ་དངུལ་བདག་སྐྱོང་དང་ རྩིས་ཞིབ་ཚོགས་ཆུང་།",
        badge: "Fiduciary Oversight",
        bgVariant: "light",
        primaryCtaText: "Investment Policy Statement",
        primaryCtaUrl: "/reports",
        secondaryCtaText: "Board of Trustees",
        secondaryCtaUrl: "/about/trustees",
      },
      {
        id: "about-comm-pillars",
        type: "feature_cards",
        order: 2,
        isVisible: true,
        title: "Committee Mandates & Investment Guidelines",
        subtitle: "Capital preservation and sovereign risk management",
        bgVariant: "warm",
        items: [
          {
            title: "Asset Management Committee (AMC)",
            description: "Oversees portfolio asset allocation across sovereign fixed income, treasury bonds, and ring-fenced international reserves.",
            icon: "Scale",
            badge: "Portfolio AMC",
          },
          {
            title: "Governance & Audit Committee (GAC)",
            description: "Maintains direct audit trails with the Royal Audit Authority (RAA) and monitors internal fiduciary compliance.",
            icon: "ShieldCheck",
            badge: "Audit GAC",
          },
          {
            title: "Capital Preservation Mandate",
            description: "Targeting conservative annual real returns of 4.5% to 5.5% while strictly avoiding speculative instruments.",
            icon: "Lock",
            badge: "Zero-Risk Mandate",
          },
          {
            title: "Liquidity Buffer",
            description: "Maintains a minimum 6-month operational liquidity reserve to buffer against international supply-chain disruptions.",
            icon: "Target",
            badge: "Supply Buffer",
          },
        ],
      },
    ],
  },
  {
    slug: "about-secretariat",
    title: "Secretariat & Organogram | Bhutan Health Trust Fund",
    metaDescription:
      "Official operational organogram, directorate leadership, and approved staffing cadre of the BHTF Secretariat.",
    isSystemPage: true,
    sections: [
      {
        id: "about-sec-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Secretariat & Organogram",
        subtitle:
          "The executive administrative apparatus executing the Royal Charter mandate, procurement logistics, and fiduciary investments.",
        dzongkhaText: "དྲུང་ཆེན་ཡིག་ཚང་དང་ བཀོད་རིམ།",
        badge: "Annexure 1 Cadre",
        bgVariant: "light",
        primaryCtaText: "Contact Secretariat",
        primaryCtaUrl: "/contact",
        secondaryCtaText: "Board of Trustees",
        secondaryCtaUrl: "/about/trustees",
      },
      {
        id: "about-sec-pillars",
        type: "feature_cards",
        order: 2,
        isVisible: true,
        title: "Operational Divisions & Staffing Hierarchy",
        subtitle: "Approved Annexure 1 Cadre under the Directorate",
        bgVariant: "white",
        items: [
          {
            title: "Directorate Leadership",
            description: "Headed by the Executive Director, providing daily leadership, multilateral liaison, and coordination with the Ministry of Health.",
            icon: "Building2",
            badge: "Director",
          },
          {
            title: "Investment Management Division",
            description: "Manages sovereign bond portfolios, fixed deposits, foreign currency ring-fenced reserves, and treasury forecasting.",
            icon: "Scale",
            badge: "Finance & Investment",
          },
          {
            title: "Programme & Procurement Division",
            description: "Coordinates national forecasting for 438 essential medicines, 110 traditional remedies, and cold-chain logistics across all 20 Dzongkhags.",
            icon: "Pill",
            badge: "Commodities Logistics",
          },
          {
            title: "Administration & Accounts Division",
            description: "Responsible for human resources, IT infrastructure, public disclosures, and fiduciary accounting.",
            icon: "Target",
            badge: "Administration",
          },
        ],
      },
    ],
  },
  {
    slug: "our-story",
    title: "Our Story & Historical Milestones | Bhutan Health Trust Fund",
    metaDescription:
      "The founding chronicle of Bhutan Health Trust Fund from the 1998 WHO Geneva launch, Royal Charter enactment by His Majesty the Fourth Druk Gyalpo, to universal healthcare security.",
    isSystemPage: true,
    sections: [
      {
        id: "our-story-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Our Story & Founding Vision",
        subtitle:
          "Over more than two decades, BHTF has grown from a visionary pledge in Geneva into an enduring national endowment sustaining primary healthcare for every Bhutanese citizen.",
        dzongkhaText: "བྱུང་རབས་དང་ རྒྱལ་པོའི་མཐོང་སྣང་།",
        badge: "The Chronicle of Health Sovereignty • 1998–2026",
        bgVariant: "dark",
        primaryCtaText: "Explore Milestones",
        primaryCtaUrl: "/our-story#milestones",
      },
    ],
  },
  {
    slug: "our-work",
    title: "Healthcare Programs & Essential Medicines | BHTF",
    metaDescription:
      "Explore the 6 core healthcare commodity financing streams supported by Bhutan Health Trust Fund across all 20 Dzongkhags.",
    isSystemPage: true,
    sections: [
      {
        id: "work-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Sovereign Healthcare Commodity Financing",
        subtitle:
          "Financing 438 essential modern medicines, 110 traditional formulations, and 4 routine national vaccines across all 20 Dzongkhags and 205 Gewogs.",
        dzongkhaText: "གཞི་རིམ་སྨན་རྫས་དང་ འགོག་ཁབ་རྒྱལ་ཡོངས་མཁོ་སྤྲོད།",
        badge: "Zero Stock-Out Mandate",
        bgVariant: "dark",
        primaryCtaText: "Contribute to Procurement",
        primaryCtaUrl: "/get-involved",
        secondaryCtaText: "Review Procurement Guidelines",
        secondaryCtaUrl: "/policies",
      },
      {
        id: "work-streams",
        type: "feature_cards",
        order: 2,
        isVisible: true,
        title: "Financing Streams & Logistics",
        subtitle: "How BHTF safeguards the medical supply line from port of entry to alpine clinics",
        bgVariant: "white",
        items: [
          {
            title: "Vital Primary & Traditional Formulary",
            description: "438 modern essential medicines and 110 indigenous gSo-ba Rig-pa formulations.",
            icon: "Pill",
            badge: "438+ Formulations",
          },
          {
            title: "Universal Routine Vaccines",
            description: "Pentavalent, PCV, HPV, and seasonal influenza vaccines sustained nationwide.",
            icon: "Syringe",
            badge: "4 Antigens",
          },
          {
            title: "Highland Cold Chain Infrastructure",
            description: "Solar direct drive refrigeration units in snowbound gewog clinics.",
            icon: "ThermometerSnowflake",
            badge: "100% Cold Chain",
          },
          {
            title: "Central Medical Stores Buffer",
            description: "Multi-month strategic emergency stockpile maintained in Phuntsholing and Thimphu.",
            icon: "Building2",
            badge: "Strategic Buffer",
          },
        ],
      },
    ],
  },
  {
    slug: "reports",
    title: "Statutory Reports & RAA Audits | Bhutan Health Trust Fund",
    metaDescription: "Annual reports, audited financial statements, and fiduciary reviews certified by the Royal Audit Authority.",
    isSystemPage: true,
    sections: [
      {
        id: "reports-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Institutional Transparency & Certified Audits",
        subtitle: "Uncompromising fiduciary integrity with statutory oversight by the Royal Audit Authority of Bhutan.",
        dzongkhaText: "ལོ་བསྟར་རྩིས་ཞིབ་དང་ དྭངས་གསལ་སྙན་ཞུ།",
        badge: "Royal Audit Authority Certified",
        bgVariant: "dark",
        primaryCtaText: "View Publications Catalog",
        primaryCtaUrl: "#catalog",
      },
      {
        id: "reports-notice",
        type: "rich_text",
        order: 2,
        isVisible: true,
        title: "Fiduciary Governance Commitment",
        subtitle: "Every Ngultrum Accounted For",
        content:
          "As an autonomous statutory trust fund created by Royal Charter, BHTF subjects its financial statements to rigorous annual audits by the Royal Audit Authority (RAA). All audit reports and annual returns are placed in the public domain for civic scrutiny.",
        bgVariant: "warm",
      },
    ],
  },
  {
    slug: "policies",
    title: "Policies, Charters & Sovereign Governance | BHTF",
    metaDescription: "Royal Charter, investment guidelines, procurement regulations, and anti-corruption policies.",
    isSystemPage: true,
    sections: [
      {
        id: "policies-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Policies & Royal Charter Governance",
        subtitle: "Statutory regulations, ethical procurement guidelines, and fiduciary bylaws.",
        dzongkhaText: "ཁྲིམས་ལུགས་དང་ བདག་སྐྱོང་ལམ་སྟོན།",
        badge: "Royal Charter Statutory Framework",
        bgVariant: "dark",
      },
    ],
  },
  {
    slug: "contact",
    title: "Contact Secretariat & Citizen Ombudsman | BHTF",
    metaDescription: "Reach the BHTF Secretariat in Thimphu for inquiries, donations, and feedback.",
    isSystemPage: true,
    sections: [
      {
        id: "contact-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Citizen Inquiries & Secretariat Contact",
        subtitle: "We welcome citizen inquiries, partnership dialogues, and donor consultations across all 20 Dzongkhags.",
        dzongkhaText: "འབྲེལ་གཏུགས་དང་ མི་སེར་བདེ་དོན།",
        badge: "Secretariat Headquarters — Thimphu",
        bgVariant: "dark",
      },
    ],
  },
  {
    slug: "news",
    title: "News, Press Bulletins & Field Dispatches | BHTF",
    metaDescription: "Official press releases, cold chain updates, and healthcare commodity dispatches from Bhutan Health Trust Fund.",
    isSystemPage: true,
    sections: [
      {
        id: "news-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Official Press Releases & Field Dispatches",
        subtitle: "Verified dispatches, procurement communiqués, and cold chain milestones across Bhutan.",
        dzongkhaText: "གནས་ཚུལ་དང་ གསལ་བསྒྲགས།",
        badge: "Institutional Press Office",
        bgVariant: "dark",
      },
    ],
  },
  {
    slug: "track-donation",
    title: "Track Donation & DRC Tax Certificate | BHTF",
    metaDescription: "Verify your healthcare contribution, confirm 1:1 RGOB Royal Match, and generate your DRC tax certificate.",
    isSystemPage: true,
    sections: [
      {
        id: "track-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Contribution Verification & Tax Vouchers",
        subtitle: "Audit your transaction reference, verify the 1:1 sovereign match, and download your sealed DRC 100% tax exemption certificate.",
        dzongkhaText: "ཞལ་འདེབས་བདེན་དཔྱད་དང་ ཁྲལ་ཡང་སྙན་ཞུ།",
        badge: "Department of Revenue & Customs Compliant",
        bgVariant: "dark",
      },
    ],
  },
  {
    slug: "get-involved",
    title: "Contribute & Get Involved | Bhutan Health Trust Fund",
    metaDescription: "Every Ngultrum matched 1:1 by the Royal Government of Bhutan. Tax deductible under DRC Bhutan regulations.",
    isSystemPage: true,
    sections: [
      {
        id: "get-involved-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Sovereign Health Philanthropy & 1:1 Royal Matching",
        subtitle: "Every Ngultrum you contribute is matched 1:1 by the Royal Government of Bhutan to finance essential medicines and vaccines in perpetuity.",
        dzongkhaText: "ཞལ་འདེབས་དང་ རྒྱབ་སྐྱོར།",
        badge: "1:1 Sovereign Matching Guaranteed",
        bgVariant: "dark",
        primaryCtaText: "Contribute Online",
        primaryCtaUrl: "/get-involved#donate-form",
      },
    ],
  },
  {
    slug: "donate",
    title: "Donate to BHTF — 1:1 RGOB Sovereign Matched Healthcare Endowment",
    metaDescription: "Make an official contribution to Bhutan Health Trust Fund. 1:1 RGOB Golden Match, DRC 100% tax exemption.",
    isSystemPage: true,
    sections: [
      {
        id: "donate-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Sovereign Healthcare Philanthropy & 1:1 RGOB Match",
        subtitle: "Every Ngultrum you contribute is matched 1:1 by the Royal Government of Bhutan to finance essential medicines and vaccines in perpetuity.",
        dzongkhaText: "ཞལ་འདེབས་དང་ རྒྱབ་སྐྱོར།",
        badge: "1:1 Sovereign Matching Guaranteed",
        bgVariant: "dark",
        primaryCtaText: "Make Online Contribution",
        primaryCtaUrl: "/donate#donate-form",
      },
    ],
  },
  {
    slug: "news-events",
    title: "Upcoming Events & National Health Symposia | BHTF",
    metaDescription: "Official calendar of upcoming vaccine rollout campaigns, donor roundtables, primary healthcare symposiums, and national health commemorations.",
    isSystemPage: true,
    sections: [
      {
        id: "events-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Upcoming Events & National Health Commemorations",
        subtitle: "Key dates for nationwide vaccine rollouts, statutory donor roundtables, technical cold chain symposia, and public health campaigns.",
        badge: "Official Event Calendar",
        bgVariant: "light",
      },
      {
        id: "events-calendar",
        type: "feature_cards",
        order: 2,
        isVisible: true,
        title: "Official Schedule of Events",
        subtitle: "Key dates for nationwide vaccine rollouts, statutory donor roundtables, and health campaigns.",
        badge: "Event Calendar",
      },
    ],
  },
  {
    slug: "news-announcements",
    title: "Statutory Announcements & Official Gazette | BHTF",
    metaDescription: "Official public notices, procurement tenders, Board resolutions, and statutory disclosures of Bhutan Health Trust Fund.",
    isSystemPage: true,
    sections: [
      {
        id: "announcements-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Statutory Announcements & Official Gazette",
        subtitle: "Official public notices, procurement tender notifications, Board resolutions, and statutory disclosures of the Bhutan Health Trust Fund.",
        badge: "Official Gazette",
        bgVariant: "light",
      },
      {
        id: "announcements-gazette",
        type: "rich_text",
        order: 2,
        isVisible: true,
        title: "Official Public Notices & Circulars",
        subtitle: "Audited official communications and policy directives.",
      },
    ],
  },
  {
    slug: "news-careers",
    title: "Career Opportunities & Institutional Vacancies | BHTF",
    metaDescription: "Join the Bhutan Health Trust Fund Secretariat. Explore executive, investment management, and procurement opportunities.",
    isSystemPage: true,
    sections: [
      {
        id: "careers-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Career Opportunities & Institutional Vacancies",
        subtitle: "Join the dedicated team managing the sovereign healthcare endowment of Bhutan. Explore professional opportunities across fiduciary management, investment operations, and public health procurement.",
        badge: "Civil Service & Trust Cadres",
        bgVariant: "light",
      },
      {
        id: "careers-roster",
        type: "feature_cards",
        order: 2,
        isVisible: true,
        title: "Open Positions & Terms of Reference",
        subtitle: "All appointments follow the BHTF Service Manual and statutory recruitment frameworks.",
      },
    ],
  },
  {
    slug: "resources-advocacy",
    title: "Advocacy Materials & Public Health Policy Briefs | BHTF",
    metaDescription: "Download BHTF healthcare advocacy publications, policy briefs, and universal health coverage research papers.",
    isSystemPage: true,
    sections: [
      {
        id: "advocacy-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Advocacy Materials & Public Health Policy Briefs",
        subtitle: "Explore publications, healthcare impact studies, stakeholder briefs, and educational material on sustainable healthcare financing in Bhutan.",
        badge: "Public Health Advocacy",
        bgVariant: "light",
      },
      {
        id: "transparency-highlights",
        type: "stats",
        order: 2,
        isVisible: true,
        title: "Advocacy Reach & Metrics",
        subtitle: "Empirical public health publications and research documents.",
      },
    ],
  },
  {
    slug: "resources-annual-reports",
    title: "Statutory Annual Reports Archive | BHTF",
    metaDescription: "Download comprehensive annual reports, financial reviews, and healthcare program outcomes of the Bhutan Health Trust Fund.",
    isSystemPage: true,
    sections: [
      {
        id: "annual-reports-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Statutory Annual Reports Archive",
        subtitle: "Download official audited annual reports chronicling financial performance, endowment yields, and primary healthcare commodity procurement since 2003.",
        badge: "Statutory Accountability",
        bgVariant: "light",
      },
      {
        id: "reports-archive",
        type: "feature_cards",
        order: 2,
        isVisible: true,
        title: "Official Annual Reports Repository",
        subtitle: "Complete annual filings certified by the Board of Trustees.",
      },
    ],
  },
  {
    slug: "resources-audit-reports",
    title: "Certified Financial Audits & Statutory Ledger | BHTF",
    metaDescription: "Download independent financial audit reports conducted by the Royal Audit Authority (RAA) of Bhutan.",
    isSystemPage: true,
    sections: [
      {
        id: "audit-reports-hero",
        type: "hero",
        order: 1,
        isVisible: true,
        title: "Certified Financial Audits & Statutory Ledger",
        subtitle: "Uncompromising fiduciary transparency. Access certified independent audit reports conducted by the Royal Audit Authority (RAA) of Bhutan.",
        badge: "Royal Audit Authority Certified",
        bgVariant: "light",
      },
      {
        id: "transparency-highlights",
        type: "stats",
        order: 2,
        isVisible: true,
        title: "100% Unqualified Audit Rating",
        subtitle: "Historical Archive Indexed from 2003 to 2026 across all statutory filings.",
      },
    ],
  },
  {
    slug: "resources-window-financing",
    title: "Window Financing Fiduciary Architecture | BHTF",
    metaDescription: "Ministry of Finance Window Financing guidelines, disbursement schedules, and requisition procedures.",
    isSystemPage: true,
    sections: [
      {
        id: "window-financing-architecture",
        type: "feature_cards",
        order: 1,
        isVisible: true,
        title: "Statutory Fiduciary Architecture & Operational Governance",
        subtitle: "Three pillars ensuring constitutional ring-fencing, zero stockouts, and total sovereign alignment.",
        badge: "Institutional Governance",
      },
      {
        id: "window-financing-guidelines",
        type: "rich_text",
        order: 2,
        isVisible: true,
        title: "Quarterly Window Financing Protocol & Disbursement Cycles",
        subtitle: "Standard operating procedures governing quarterly releases from BHTF to DMS/MOF.",
      },
    ],
  },
];
